const bookDataSeed = [
  {
    userId: 1,
    title: 'Tôi thấy hoa vàng trên cỏ xanh',
    author: 'Nguyễn Nhật Ánh',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fdfe',
  },
  {
    userId: 1,
    title: 'Những cuộc phiêu lưu của Tom Sawyer',
    author: 'Mark Twain',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fdff',
  },
  {
    userId: 1,
    title: 'Chậm Lại Cùng Con Thưởng Thức Thời Thơ Ấu',
    author: 'Nhiêu Tuyết Lị',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe00',
  },
  {
    userId: 1,
    title: 'Tủ Sách Thiên Thần - Tập 6: Thoát Khỏi Mê Cung',
    author: 'Koji Yanagi',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe01',
  },
  {
    userId: 1,
    title: 'Joker Game - Tập 1',
    author: 'Koji Yanagi',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe02',
  },
  {
    userId: 1,
    title: 'Ngọc Sáng Trong Hoa Sen (Tái Bản 2015)',
    author: 'John Blofeld',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe03',
  },
  {
    userId: 1,
    title: 'Tạm Biệt, Em Ổn!',
    author: 'Tờ Pi',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe04',
  },
  {
    userId: 1,
    title: 'Kỳ Nghỉ Hè Tươi Đẹp',
    author: 'Dương Chí Thành',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe05',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 12 (2019) - Bài Học (Bộ 14 Cuốn)',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe06',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 11 (2019) - Bài Học (Bộ 14 Cuốn)',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe07',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 10 (2019) - Bài Học (Bộ 14 Cuốn)',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe08',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 9 (2019) - Bài Học (Bộ 12 Cuốn)',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe09',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 8 (2019) - Bài Học (Bộ 13 Cuốn)',
    author: 'Nhiều Tác Giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0a',
  },
  {
    userId: 1,
    title: 'Bộ Sách Giáo Khoa Lớp 7 (2019) - Bài Học (Bộ 12 Cuốn)',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0b',
  },
  {
    userId: 1,
    title: 'Cơn Cao Hứng Đáng Giá Ngàn Vàng',
    author: 'Lê Thiếu Nhơn',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0c',
  },
  {
    userId: 1,
    title: 'Chúng Ta Đều Sợ Tổn Thương',
    author: 'Đới Quân',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0d',
  },
  {
    userId: 1,
    title: 'Khôn Ngoan Vừa Đủ, Làm Chủ Cuộc Đời',
    author: 'Vũ Mãn Lan Giang',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0e',
  },
  {
    userId: 1,
    title: 'Hồi Ký Tiến Sĩ Lê Thẩm Dương',
    author: 'Nguyễn Tuấn Anh',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe0f',
  },
  {
    userId: 1,
    title: 'Em Luôn Đúng, Em Yêu!',
    author: 'Dung Quang',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe10',
  },
  {
    userId: 1,
    title: 'Chưa Đủ Cô Đơn Để Yêu Chăng?',
    author: 'G  ',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe11',
  },
  {
    userId: 1,
    title: 'Combo Thư Ký Kim Sao Thế? (Bộ 2 Tập) (Tặng Kèm 1 Quyển Photobook)',
    author: 'Jeong Gyeong Yun',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe12',
  },
  {
    userId: 1,
    title: 'Phải Lòng Với Cô Đơn',
    author: 'Kulzsc',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe13',
  },
  {
    userId: 1,
    title: 'Tôi Có Một Chén Rượu, Có Thể Xoa Dịu Hồng Trần',
    author: 'Quan Đông Dã Khách',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe14',
  },
  {
    userId: 1,
    title: 'Rồi Cũng Phải Quen Với Sự Cô Đơn',
    author: 'Nhị Hy',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe15',
  },
  {
    userId: 1,
    title: 'Những Điều Giữ Tôi Còn Sống',
    author: 'Matt Haig',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe16',
  },
  {
    userId: 1,
    title: 'Ơ Kìa Nước Mỹ! - Eureka America',
    author: 'Phan Quốc Vinh',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe17',
  },
  {
    userId: 1,
    title: 'Thế Hệ Y Lên Ngôi',
    author: 'Maddie Grant',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe18',
  },
  {
    userId: 1,
    title: 'Để Xây Dựng Doanh Nghiệp Hiệu Quả (Tái Bản 2019)',
    author: 'Michael E. Gerber',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe19',
  },
  {
    userId: 1,
    title: 'Thiết Kế Lấy Người Dùng Làm Trung Tâm',
    author: 'Don Norman',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1a',
  },
  {
    userId: 1,
    title: 'Lãnh Đạo Sáng Tạo',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1b',
  },
  {
    userId: 1,
    title: 'Xây Dựng Nhóm Hiệu Quả Dành Cho Nhà Quản Lý Bận Rộn',
    author: 'Brian Cole Miller',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1c',
  },
  {
    userId: 1,
    title: '75 Điều Những Bậc Cha Mẹ Tuyệt Vời Thường Làm',
    author: 'Erica Reischer',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1d',
  },
  {
    userId: 1,
    title: 'Vào Bếp Nấu Ăn - Săn Ngay Điểm Tốt',
    author: 'Đỗ Xuân Thảo',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1e',
  },
  {
    userId: 1,
    title: 'Cẩm Nang "Sống Sót" Cho Cha Mẹ Có Con 2 - 7 Tuổi',
    author: 'Julie King',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe1f',
  },
  {
    userId: 1,
    title: 'Chăm Sóc Sức Khỏe Trẻ Em - Tập 8: Bệnh Dị Ứng',
    author: 'Thôi Ngọc Đào',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe20',
  },
  {
    userId: 1,
    title: 'Tuổi Thơ Tìm Thấy',
    author: 'Carl Honoré',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe21',
  },
  {
    userId: 1,
    title: 'Thiền Tập Cho Con',
    author: 'David Fontana',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe22',
  },
  {
    userId: 1,
    title: 'Biệt Đội Siêu Quậy - Tập 1: Bí Mật Về "Đế Chế Khủng Long"',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe23',
  },
  {
    userId: 1,
    title: 'Kiên Trì Không Bỏ Cuộc (Song Ngữ) - Tái Bản 2019',
    author: 'Jennifer Moore-Mallinos',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe24',
  },
  {
    userId: 1,
    title: 'Đếm Sao',
    author: 'Lois Lowry',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe25',
  },
  {
    userId: 1,
    title: 'Combo Ehon Nhật Bản - Bé Mèo Nontan (Bộ 6 Tập)',
    author: 'Sachiko Kiyono',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe26',
  },
  {
    userId: 1,
    title: 'Lời Ru Của Mẹ - Tập 1',
    author: 'Đặng Phương Anh',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe27',
  },
  {
    userId: 1,
    title: 'Những Quy Tắc Trong Tình Yêu (Tái Bản 2019)',
    author: 'Richard Templar',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe28',
  },
  {
    userId: 1,
    title: 'Dám Thay Đổi',
    author: 'Susyn Reeve',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe29',
  },
  {
    userId: 1,
    title: 'Không Việc Gì Phải Vội!',
    author: 'Carl Honoré',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe2a',
  },
  {
    userId: 1,
    title: 'Bên Kia Những Vì Sao',
    author: 'Osho',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe2b',
  },
  {
    userId: 1,
    title: 'J.O.Y - Inspiration For Everyday Life - Issue 1: Lấp Lánh',
    author: 'Nhiều tác giả',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe2c',
  },
  {
    userId: 1,
    title: 'Sức Mạnh Của Sự Quan Tâm',
    author: 'Ken Blanchard',
    publicYear: 2015,
    voiceId: null,
    bitRate: null,
    rate: null,
    soundBackground: null,
    usedSoundBackground: null,
    soundBackgroundVolumn: null,
    chapterIds: [],
    status: [],
    _id: '5d9c063c9323554bd8f6fe2d',
  },
];

module.exports = {
  bookDataSeed,
};
